"""Initial migration

Revision ID: f541e2ec362c
Revises: 
Create Date: 2026-01-21 22:46:39.972152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f541e2ec362c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('cliente_id', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('contato', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_table('enderecos',
    sa.Column('endereco_id', sa.String(length=255), nullable=False),
    sa.Column('rua', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('endereco_id')
    )
    op.create_table('proprietarios',
    sa.Column('proprietario_id', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('contato', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('proprietario_id')
    )
    op.create_table('hospedagens',
    sa.Column('hospedagem_id', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('endereco_id', sa.String(length=255), nullable=True),
    sa.Column('proprietario_id', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.endereco_id'], ),
    sa.ForeignKeyConstraint(['proprietario_id'], ['proprietarios.proprietario_id'], ),
    sa.PrimaryKeyConstraint('hospedagem_id')
    )
    op.create_table('alugueis',
    sa.Column('aluguel_id', sa.String(length=255), nullable=False),
    sa.Column('cliente_id', sa.String(length=255), nullable=True),
    sa.Column('hospedagem_id', sa.String(length=255), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('preco_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.ForeignKeyConstraint(['hospedagem_id'], ['hospedagens.hospedagem_id'], ),
    sa.PrimaryKeyConstraint('aluguel_id')
    )
    op.create_table('avaliacoes',
    sa.Column('avaliacao_id', sa.String(length=255), nullable=False),
    sa.Column('cliente_id', sa.String(length=255), nullable=True),
    sa.Column('hospedagem_id', sa.String(length=255), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.ForeignKeyConstraint(['hospedagem_id'], ['hospedagens.hospedagem_id'], ),
    sa.PrimaryKeyConstraint('avaliacao_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacoes')
    op.drop_table('alugueis')
    op.drop_table('hospedagens')
    op.drop_table('proprietarios')
    op.drop_table('enderecos')
    op.drop_table('clientes')
    # ### end Alembic commands ###